import { StyleSheet } from "react-native";
export const GREEN = "#1a6b3c";
const BG = "#f5f5f0";

export const roundSummaryStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: BG },
    content: { padding: 20, paddingBottom: 60 },
    headerCard: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 20,
        alignItems: "center",
        marginBottom: 16,
        marginTop: 48,
    },
    completedLabel: {
        fontSize: 11,
        fontWeight: "700",
        color: GREEN,
        letterSpacing: 1.5,
        marginBottom: 6,
    },
    courseName: {
        fontSize: 16,
        fontWeight: "700",
        color: "#1a1a2e",
        marginBottom: 8,
    },
    score: {
        fontSize: 36,
        fontWeight: "800",
        color: "#1a1a2e",
    },
    scoreDiff: {
        fontSize: 22,
        fontWeight: "700",
    },
    handicap: {
        fontSize: 13,
        color: "#888",
        marginTop: 4,
    },
    statsRow: {
        flexDirection: "row",
        gap: 12,
        marginBottom: 12,
    },
    statCard: {
        flex: 1,
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 16,
        gap: 4,
    },
    statLabel: { fontSize: 12, color: "#888" },
    statValue: { fontSize: 22, fontWeight: "800", color: "#1a1a2e" },
    progressBar: {
        height: 4,
        backgroundColor: "#eee",
        borderRadius: 2,
        marginTop: 4,
        overflow: "hidden",
    },
    progressFill: {
        height: 4,
        backgroundColor: GREEN,
        borderRadius: 2,
    },
    sectionRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 10,
    },
    sectionTitle: { fontSize: 16, fontWeight: "700", color: "#1a1a2e" },
    scorecard: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 12,
        marginBottom: 8,
    },
    scorecardRow: { flexDirection: "row", alignItems: "center", marginBottom: 8 },
    scorecardLabelCell: { width: 44, marginRight: 4 },
    scorecardCell: { width: 36, alignItems: "center" },
    scorecardHeader: { fontSize: 12, fontWeight: "700", color: "#1a1a2e" },
    scorecardSubHeader: { fontSize: 12, fontWeight: "600", color: "#888" },
    scorecardPar: { fontSize: 12, color: "#555" },
    scoreCircle: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: "center",
        justifyContent: "center",
        borderWidth: 1,
        borderColor: "#ddd",
    },
    scoreCircleText: { fontSize: 11, fontWeight: "700" },
    scrollHint: { fontSize: 11, color: "#aaa", textAlign: "center", marginBottom: 20 },
    saveButton: {
        backgroundColor: GREEN,
        borderRadius: 14,
        paddingVertical: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
        marginBottom: 12,
    },
    saveButtonText: { color: "#fff", fontSize: 15, fontWeight: "700" },
    shareButton: {
        backgroundColor: "#fff",
        borderRadius: 14,
        paddingVertical: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 10,
    },
    shareButtonText: { color: "#555", fontSize: 15, fontWeight: "600" },
});
